# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Baby Bindery Test Site!
email: lukas@thedesignoffice.org
description: > # this means to ignore newlines until "baseurl:"
  Web-to-Print framework, templated using Jekyll. By Catherine Schmidt and Lukas WinklerPrins, for The Design Office PVD. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thedesignoffice.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
