# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Baby Bindery
email: john@thedesignoffice.org
description: > # this means to ignore newlines until "baseurl:"
  Web-to-Print framework, templated using Jekyll. By Catherine Leigh Schmidt and Lukas WinklerPrins, for The Design Office PVD with John Caserta.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thedesignoffice.github.io/babybindery/" # the base hostname & protocol for your site
twitter_username:
github_username: thedesignoffice
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
page_width: "8.5in"
page_height: "11in"
content_types: [conversation, image, text]
